Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls', namespace='blog',)),
    path('blog-admin/', include('adminapp.urls', namespace="blog_admin"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/urls.py
from django.urls import path
from adminapp import views

app_name = 'blog_admin'

urlpatterns = [
path('admin-home', views.home, name='admin_home'),
path('add-post', views.add_post, name='add_post'),
path('check-title-exist', views.check_title_exist, name='check_title_exist'),
path('save-post', views.save_post, name='save_post'),
path('admin-profile', views. admin_profile, name='admin_profile'),
path('edit-profile', views.edit_profile, name='edit_profile'),
path('save-profile', views.save_profile, name='save_profile'),
]

templates/admin_templates/add_post.html
{% extends 'admin_templates/base.html' %}

{% block main_content %}

<div class="main-body">
    <div class="page-wrapper">
        <div class="page-body">
            <div class="row">
                <div class="col-sm-12">
                    <!-- Basic Form Inputs card start -->
                    <div class="card">
                        <div class="card-header">
                            <h5>Add Post</h5>
                        </div>
                        <div class="card-block">
                            <h4 class="sub-title">Fill in the fields to add a post.</h4>
                            <form role="form" method="post" action="{% url 'blog_admin:save_post' %}" enctype="multipart/form-data">
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">Title:</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="title" name="title">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">Author's Name:</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" value="{{ users.username }}" placeholder="{{ users.username}}">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">Post Body</label>
                                    <div class="col-sm-10">
                                        <textarea rows="15" cols="10" class="form-control" placeholder="Post Body" name="post_body"></textarea>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">Extra Body</label>
                                    <div class="col-sm-10">
                                        <textarea rows="15" cols="10" class="form-control" placeholder="Extra Body" name="extra_body"></textarea>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">Post Image:</label>
                                    <div class="col-sm-10">
                                        <input type="file" class="form-control" name="post_image">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">Post video:</label>
                                    <div class="col-sm-10">
                                        <input type="file" class="form-control" name="post_video">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">Select Category</label>
                                    <div class="col-sm-10">
                                        <select name="categories" class="form-control">
                                            {% for post in posts %}
                                            <option value="{{ post }}">{{ post.Categories.HTML }}</option>
                                            <option value="{{ post.id }}">{{ post.Categories.CSS }}</option>
                                            <option value="{{ post.id }}">{{ post.Categories.JAVASCRIPTS }}</option>
                                            <option value="{{ post.id }}">{{ post.Categories.PYTHON }}</option>
                                            <option value="{{ post.id }}">{{ post.Categories.DJANGO }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">Status</label>
                                    <div class="col-sm-10">
                                        <select name="status" class="form-control">
                                            {% for post in posts %}
                                            <option value="{{ post.Status }}">{{ post.Status.DRAFT }}</option>
                                            <option value="{{ post.id }}">{{ post.Status.PUBLISHED}}</option>
                                            <option value="{{ post.id }}">{{ post.Status.TRENDING }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">Publish Date:</label>
                                    <div class="col-sm-10">
                                        <div class="form-control-static">
                                            Date: <input type="date" name="publish_date"  size="10" required="" id="publish_date" >
                                            Time: <input type="time" name="publish_date"  size="10" required="" id="publish_date" >
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">Slug:</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" placeholder="A hypen-separated list of title words" name="slug">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">Add Tags:</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" placeholder="A comma-separated list of tags." name="tags">
                                    </div>
                                </div>
                                <div class ="col-lg-12">
                                    {% if messages %}                           
                                    {% for message in messages %}
                                    {% if message.tags == 'error' %}
                                    <div class="card card-danger" style="margin-top:10px">
                                      <div class="card-header">
                                        <h3 class="card-title">{{ message }}</h3>
                                        <div class="card-tools">
                                            <button type="button" class="btn btn-tool" data-card-widget="remove">
                                              <i class="fas fa-times"></i></button>
                                        </div>
                                      </div>
                                    </div>
                                    {% endif %}
                                    {% if message.tags == 'success' %}
                                    <div class="card card-success" style="margin-top:10px">
                                      <div class="card-header">
                                        <h3 class="card-title">{{ message }}</h3>
                                        <div class="card-tools">
                                            <button type="button" class="btn btn-tool" data-card-widget="remove">
                                              <i class="fa fa-times"></i></button>
                                        </div>
                                      </div>
                                    </div>
                                    {% endif %}
                                    {% endfor %}
                                    {% endif %}
                                  </div>
                                <div class="row m-t-30">
                                    <div class="col-md-12">
                                        <button type="submit" class="btn btn-primary btn-md btn-block waves-effect waves-light text-center m-b-20">Upload Post.</button>
                                    </div>
                                </div>
                                <hr/>
                            </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

  {% endblock main_content %}

{% block custom_js %}  
<script>
    $(document).ready(function(){
        $("#title").keyup(function(){
            let titlle = $(this).val();
            if(title!=""){
                $.ajax({
                    url: '{% url 'blog_admin:check_title_exist' %}',
                    type: 'POST',
                    data: {title=title}
                })
                .done(function(response){
                    console.log(response);
                    if(response=="True"){
                        $(".email_error").remove();
                        $("<span class='email_error' style='padding: 5px;color: red;font-weight: bold;'>Email already taken!</span>").insertAfter("#title");
                    }
                    else{
                        $(".email_error").remove();
                        $("<span class='email_error' style='padding: 5px;color: green;font-weight: bold;'>Email Available</span>").insertAfter("#title");
                    }
                })
                .fail(function(){
                    console.log("failed");
                })
            }
            else{
                $(".email_error").remove();
              }
        });

        $('#publish_date').datepicker({
            changeMonth: true,
            changeYear: true,
          });
    });
</script>

{% endblock custom_js %}

templates/admin_templates/admin_profile.html
{% extends 'admin_templates/base.html' %}
{% load static %}

{% block main_content %}

<div class="wrapper">
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                  <div class="col-sm-6">
                    <h1>Profile</h1>
                  </div>
                </div>
            </div>
        </section>

        <section class="content">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-6">

                <!-- Profile Image -->
            <div class="card card-primary card-outline">
                <div class="card-body box-profile">
                  <div class="text-center">
                    <img class="profile-user-img img-fluid img-circle"
                         src="{{ admin_id.profile_pic.url }}" alt="User profile pictures">
                  </div>
  
                  <h3 class="profile-username text-center">{{ user.first_name }} {{ user.last_name  }}</h3>
  
                  <p class="text-muted text-center">Software Engineer</p>
  
                  <ul class="list-group list-group-unbordered mb-3">
                    <li class="list-group-item">
                      <b>Total Posts:</b> <a class="float-right">{{ post_count }}</a>
                    </li>
                    <li class="list-group-item">
                      <b>Total Comments:</b> <a class="float-right">{{ comment_count }}</a>
                    </li>
                    <li class="list-group-item">
                      <b>Phone Number:</b> <a class="float-right">{{ admin_id.phone_no }}</a>
                    </li>
                  </ul>
  
                  <a href="#" class="btn btn-primary btn-block"><b>Follow</b></a>
                </div>
                <!-- /.card-body -->
              </div>

              </div>
            </div>
           </div>
        </section>

    </div>
</div>

{% endblock main_content %}

templates/admin_templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Emmi_Blog Admin{% endblock title %}</title>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <meta name="keywords" content="{% block keywords %}Emmi Blog admin, manage all your blog posts and your profile here.{% endblock keywords %}" />
    <meta name="author" content="Emmi_Dev" />
    <!-- Favicon icon -->
    <link rel="icon" href="{% static 'admin-assets/img/favicon.ico' %}" type="image/x-icon">
    <!-- Google font-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet">
    <!-- waves.css -->
    <link rel="stylesheet" href="{% static 'admin-assets/css/waves.min.css' %}" type="text/css" media="all">
    <!-- Required Fremwork -->
    <link rel="stylesheet" type="text/css" href="{% static 'admin-assets/css/bootstrap.min.css' %}">
    <!-- waves.css -->
    <link rel="stylesheet" href="{% static 'admin-assets/css/waves.min.css' %}" media="all">
    <!-- themify icon -->
    <link rel="stylesheet" type="text/css" href="{% static 'admin-assets/css/themify-icons.css' %}">
    <!-- font-awesome-n -->
    <link rel="stylesheet" type="text/css" href="{% static 'admin-assets/css/font-awesome-n.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'admin-assets/css/font-awesome.min.css' %}">
    <!-- scrollbar.css -->
    <link rel="stylesheet" type="text/css" href="{% static 'admin-assets/css/jquery.mCustomScrollbar.css' %}">
    <!-- Style.css -->
    <link rel="stylesheet" type="text/css" href="{% static 'admin-assets/css/style.min.css' %}">
    <!-- ico font -->
    <link rel="stylesheet" type="text/css" href="{% static 'admin-assets/css/icofont.css' %}">
    {% block Stylesheet %} {% endblock Stylesheet %}

</head>

<body>
    <!-- Pre-loader start -->
    {% include 'admin_templates/includes/preloader.html' %}
    <!-- Pre-loader end -->
    <div id="pcoded" class="pcoded">
        <div class="pcoded-overlay-box"></div>
        <div class="pcoded-container navbar-wrapper">
            <!-- Navbar start -->
            {% include 'admin_templates/includes/navbar.html' %}
            <!-- Navbar ends -->

            <div class="pcoded-main-container">
                <div class="pcoded-wrapper">
                    <!-- Sidebar start-->
                    {% include 'admin_templates/includes/sidebar.html' %}
                    <!-- Sidebar ends -->

                    <div class="pcoded-content">
                        <!-- Page-header start -->
                        <div class="page-header">
                            <div class="page-block">
                                <div class="row align-items-center">
                                    <div class="col-md-8">
                                        <div class="page-header-title">
                                            <h5 class="m-b-10">{% block dashboard %}Dashboard {% endblock dashboard %}</h5>
                                            <p class="m-b-0">{% block welcome %} Welcome to your Blog  {% endblock welcome %} </p>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <ul class="breadcrumb">
                                            <li class="breadcrumb-item">
                                                <a href="index.html"> <i class="fa fa-home"></i> </a>
                                            </li>
                                            <li class="breadcrumb-item"><a href="#!">Dashboard</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Page-header end -->
                        <div class="pcoded-inner-content">
                            <!-- Main-body start -->
                         {% block main_content %}


                         {% endblock main_content %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  

    <!-- Required Jquery -->
    <script type="text/javascript" src="{% static 'admin-assets/js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin-assets/js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin-assets/js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin-assets/js/bootstrap.min.js' %}"></script>
    <!-- waves js -->
    <script src="{% static 'admin-assets/js/waves.min.js' %}"></script>
    <!-- jquery slimscroll js -->
    <script type="text/javascript" src="{% static 'admin-assets/js/jquery.slimscroll.js' %}"></script>

    <!-- slimscroll js -->
    <script src="{% static 'admin-assets/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>

    <!-- menu js -->
    <script src="{% static 'admin-assets/js/pcoded.min.js' %}"></script>
    <script src="{% static 'admin-assets/js/vertical-layout.min.js' %}"></script>
    <script src="{% static 'admin-assets/js/accordion.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin-assets/js/script.min.js' %}"></script>
    {% block custom_js %} 
    
    {% endblock custom_js %}
</body>

</html>

templates/admin_templates/edit-profile.html
{% extends 'admin_templates/base.html' %}
{% load static %}
{% block Stylesheet %} 
    <link rel="stylesheet" href="{% static 'admin-assets/css/all.min.css' %}">
      <!-- SweetAlert2 -->
    <link rel="stylesheet" href="{% static 'admin-assets/css/bootstrap-4.min.css' %}">
    <!-- Toastr -->
    <link rel="stylesheet" href="{% static 'admin-assets/css/toastr.min.css' %}">


{% endblock Stylesheet %}

{% block main_content %}

<div class="main-body">
    <div class="page-wrapper">
        <div class="page-body">
            <div class="row">
                <div class="col-sm-12">
                    <!-- Basic Form Inputs card start -->
                    <div class="card">
                        <div class="card-header">
                            <h5>Edit Profile</h5>
                        </div>
                        <div class="card-block">
                            <h4 class="sub-title">Fill in the fields to make changes to your profile.</h4>
                            <form method='post' action="{% url 'blog_admin:save_profile' %}" class="md-float-material form-material" enctype="multipart/form-data">
                                {% csrf_token %}
                             
                             <div class="auth-box card">
                                     <div class="form-group form-primary">
                                         <input type="text" name="username" class="form-control required fill" value="{{ user.username }}" required disabled>
                                         <span class="form-bar"></span>
                                         <label class="float-label">Username</label>
                                     </div>
                                     <div class="form-group form-primary">
                                        <input type="email" name="user_email" class="form-control required fill" value="{{ user.email }}" required disabled>
                                        <span class="form-bar"></span>
                                        <label class="float-label">Email</label>
                                    </div>
                                     <div class="form-group form-primary">
                                         <input type="text" name="first_name" class="form-control required fill" value="{{ user.first_name }}" required>
                                         <span class="form-bar"></span>
                                         <label class="float-label">First Name</label>
                                     </div>
                                     <div class="form-group form-primary">
                                        <input type="text" name="last_name" class="form-control required fill" value="{{ user.last_name }}" required>
                                        <span class="form-bar"></span>
                                        <label class="float-label">Last Name</label>
                                    </div>
                                    <div class="form-group form-primary">
                                        <input type="number" name="phone_num" class="form-control required fill" value="{{ admin.phone_no }}" required>
                                        <span class="form-bar"></span>
                                        <label class="float-label">Phone Number</label>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-sm-2 col-form-label">Profile Picture</label>
                                        <div class="col-sm-10">
                                            <input type="file" class="form-control" name="profile_pic" value="{{ admin.phone_no }}">
                                        </div>
                                    </div>
                                    <div class="form-group form-primary">
                                        <input type="password" name="password" class="form-control required" required>
                                        <span class="form-bar"></span>
                                        <label class="float-label">Password</label>
                                    </div>
                                    <div class="form-group">
                                        {% if messages %}
                                          {% for message in messages %}
                                          {% if message.tags == 'error' %}
                                          <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                                          {% endif %}
                                          {% if message.tags == 'success' %}
                                          <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                                          {% endif %}
                                          {% endfor %}
                                        {% endif %}
                                      </div>
                                     <div class="row m-t-30">
                                         <div class="col-md-12">
                                             <button type="submit" class="btn btn-primary btn-md btn-block waves-effect waves-light text-center m-b-20 swalDefaultSuccess">Save Changes.</button>
                                         </div>
                                     </div>
                                     <hr/>
                                 </div>
                             </div>
                         </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>





{% endblock main_content %}