Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls', namespace='blog',)),
    path('blog-admin/', include('adminapp.urls', namespace="blog_admin"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/urls.py
from django.urls import path
from blogapp import views

app_name = 'blog'

urlpatterns = [
path('', views.index, name='index'),
path('categories', views.categories, name='categories'),
path('categories/tag/<slug:tag_slug>', views.categories, name='post_list_by_tag'),
path('categories/html', views.html, name='html'),
path('categories/css', views.css, name='css'),
path('categories/js', views.js, name='js'),
path('categories/python', views.python, name='python'),
path('categories/django', views.django, name='django'),
path('about', views.about, name='about'),
path('contact', views.contact, name='contact'),
path('<int:year>/<int:month>/<int:day>/<slug:post>', views.post_detail, name='post_detail'),
path('share-post/<int:post_id>', views.share_post, name='share_post'),
path('<int:post_id>/comment', views.post_comment, name='post_comment'),
path('login', views.user_login, name='login'),
path('DoLogin', views.DoLogin, name='do_login'),
path('logout', views.user_logout, name='logout'),
]

templates/blog_templates/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %}Emmi Blog | Home {% endblock title %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'blog-assets/img/logo.png' %}" rel="icon">
  <link href="/static/blog-assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500&family=Inter:wght@400;500&family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'blog-assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'blog-assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'blog-assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <link href="{% static 'blog-assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'blog-assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <!-- Template Main CSS Files -->
  <link href="{% static 'blog-assets/css/variables.css' %}" rel="stylesheet">
  <link href="{% static 'blog-assets/css/main.css' %}" rel="stylesheet">
  {% block Stylesheet %} 
  
  {% endblock Stylesheet %}

</head>

<body class="hold-transition sidebar-mini">

  <!-- ======= Header ======= -->
  <header id="header" class="header d-flex align-items-center fixed-top">
    {% include 'blog_templates/includes/header.html' %}
  </header>
  <!-- End Header -->
    
  {% block main_content %}



  {% endblock main_content %}


  {% block footer %}
  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="footer-content">
      <div class="container">

        <div class="row g-5">
          <div class="col-lg-4">
            <h3 class="footer-heading">About Emmi Blog</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam ab, perspiciatis beatae autem deleniti voluptate nulla a dolores, exercitationem eveniet libero laudantium recusandae officiis qui aliquid blanditiis omnis quae. Explicabo?</p>
            <p><a href="{% url 'blog:about' %}" class="footer-link-more">Learn More</a></p>
          </div>
          <div class="col-6 col-lg-2">
            <h3 class="footer-heading">Navigation</h3>
            <ul class="footer-links list-unstyled">
              <li><a href="{% url 'blog:index' %}"><i class="bi bi-chevron-right"></i> Blog</a></li>
              <li><a href="{% url 'blog:categories' %}"><i class="bi bi-chevron-right"></i> Categories</a></li>
              <li><a href="{% url 'blog:about' %}"><i class="bi bi-chevron-right"></i> About us</a></li>
              <li><a href="{% url 'blog:contact' %}"><i class="bi bi-chevron-right"></i> Contact</a></li>
              <li><a href="{% url 'blog:login' %}"><i class="bi bi-chevron-right"></i> Login</a></li>
            </ul>
          </div>
          <div class="col-6 col-lg-2">
            <h3 class="footer-heading">Categories</h3>
            <ul class="footer-links list-unstyled">
              <li><a href="{% url 'blog:html' %}"><i class="bi bi-chevron-right"></i> HTML</a></li>
              <li><a href="{% url 'blog:css' %}"><i class="bi bi-chevron-right"></i> CSS</a></li>
              <li><a href="{% url 'blog:js' %}"><i class="bi bi-chevron-right"></i> JavaScript</a></li>
              <li><a href="{% url 'blog:python' %}"><i class="bi bi-chevron-right"></i> Python</a></li>
              <li><a href="{% url 'blog:django' %}"><i class="bi bi-chevron-right"></i> Django</a></li>
            </ul>
          </div>

          {% show_recent_posts %}

          </div>
        </div>
      </div>
    </div>

    <div class="footer-legal">
      <div class="container">

        <div class="row justify-content-between">
          <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
            <div class="copyright">
              &copy; Copyright <strong><span>Emmi Blog</span></strong>. All Rights Reserved
            </div>

            <div class="credits">
              Developed by <a href="https://twitter.com/emmi_dev01">Emmi Dev</a>
            </div>

          </div>

          <div class="col-md-6">
            <div class="social-links mb-3 mb-lg-0 text-center text-md-end">
              <a target='_blank' href="https://www.facebook.com/profile.php?id=100077257599929" class="mx-2"><span class="bi-facebook"></span></a>
              <a target='_blank' href="https://twitter.com/emmi_dev01" class="mx-2"><span class="bi-twitter"></span></a>
              <a target='_blank' href="https://www.youtube.com/@emmidev" class="mx-2"><span class="bi-youtube"></span></a>
            </div>

          </div>

        </div>

      </div>
    </div>

  </footer>

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'blog-assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'blog-assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'blog-assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'blog-assets/vendor/aos/aos.js' %}"></script>
    <!-- Template Main JS File -->
    <script src="{% static 'blog-assets/js/main.js' %}"></script>
  
  <!-- Custom Js -->

</body>

</html>
{% endblock footer %}

templates/blog_templates/category.html
{% extends 'blog_templates/base.html' %}
{% load blog_tags %}
{% load static %}

{% block main_content%}

  <main id="main">
    <section>
      <div class="container">
        <div class="row">

          <div class="col-md-9" data-aos="fade-up">
            {% if query %}
            <h3 class="category-title">You searched for: "{{ query }}"</h3>
            <div class="post-meta">
                <h3 class="category-title">
                  {% with results.count as total_result %} 
                  found {{ total_result }} result{{ total_result|pluralize}}
                  {% endwith %}
                </h3>
              </div>
              {% for post in results %}
            <h3 class="category-title">Category: {{ post.categories }}</h3>
            {% if tag %}
            <h5> Posts tagged with {{ tag.name }} <h5>
              {% endif %}
            <div class="post-meta">
              <h3 class="category-title">Tags:
                {% for tag in post.tags.all %} 
                <a class="caption" href="{% url "blog:post_list_by_tag" tag.slug %}">
                  {{ tag.name }} </a> {% if not forloop.last %}| {% endif %}
                {% endfor %}
              </h3>
            </div>

            <div class="d-md-flex post-entry-2 half">
              <a href="{{ post.get_absolute_url }}" class="me-4 thumbnail">
                <img src="{{ post.image.url }}" alt="" class="img-fluid">
              </a>
              <div>
                <div class="post-meta"><span class="date">{{ post.categories }}</span> <span class="mx-1">&bullet;</span> <span>{{ post.publish }}</span></div>
                <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                <p>{{ post.body|truncatewords:45|linebreaks }}</p>
                <div class="d-flex align-items-center author">
                  <div class="photo"><img src="{{ post.author_pic.url }}" alt="" class="img-fluid"></div>
                  <div class="name">
                    <h3 class="m-0 p-0">{{ post.author.first_name }} {{ post.author.last_name }}</h3>
                  </div>
                </div>
              </div>
            </div>
             {% endfor %}
             {% include 'blog_templates/includes/paginator.html' with page=search_page_object %}

          <div class="col-md-3">
            <!-- ======= Sidebar ======= -->
            <div class="aside-block">

              <ul class="nav nav-pills custom-tab-nav mb-4" id="pills-tab" role="tablist">
                <li class="nav-item" role="presentation">
                  <button class="nav-link active" id="pills-popular-tab" data-bs-toggle="pill" data-bs-target="#pills-popular" type="button" role="tab" aria-controls="pills-popular" aria-selected="true">Popular</button>
                </li>
                <li class="nav-item" role="presentation">
                  <button class="nav-link" id="pills-trending-tab" data-bs-toggle="pill" data-bs-target="#pills-trending" type="button" role="tab" aria-controls="pills-trending" aria-selected="false">Trending</button>
                </li>
                <li class="nav-item" role="presentation">
                  <button class="nav-link" id="pills-latest-tab" data-bs-toggle="pill" data-bs-target="#pills-latest" type="button" role="tab" aria-controls="pills-latest" aria-selected="false">Latest</button>
                </li>
              </ul>

              <div class="tab-content" id="pills-tabContent">

                 <!-- Popular -->
                 {% get_most_commented_post as commented_post %}
                 <div class="tab-pane fade show active" id="pills-popular" role="tabpanel" aria-labelledby="pills-popular-tab">
                  {% for post in commented_post %}
                  <div class="post-entry-1 border-bottom">
                    <div class="post-meta"><span class="date">{{ post.categories }}</span> <span class="mx-1">&bullet;</span> <span>{{ post.publish }}</span></div>
                    <h2 class="mb-2"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                    <span class="author mb-3 d-block">{{ post.author.first_name}} {{ post.author.last_name}}</span>
                  </div>
                  {% endfor %}
              </div>     
               <!-- End Popular -->

              <!-- Trending -->
              {% show_trending_post %} 
              <!-- End Trending -->

              <!-- Latest -->
              {% show_latest_posts %} 
               <!-- End Latest -->
              

              </div>
            </div>

            <div class="aside-block">
              <h3 class="aside-title">Video</h3>
              <div class="video-post">
                <a href="{{ post.video.url }}" class="glightbox link-video">
                  <span class="bi-play-fill"></span>
                  <img src="assets/img/post-landscape-5.jpg" alt="" class="img-fluid">
                </a>
              </div>
            </div><!-- End Video -->

            <div class="aside-block">
              <h3 class="aside-title">Categories</h3>
              <ul class="aside-links list-unstyled">
                <li><a href="{% url 'blog:html' %}"><i class="bi bi-chevron-right"></i> HTML</a></li>
                <li><a href="{% url 'blog:css' %}"><i class="bi bi-chevron-right"></i> CSS</a></li>
                <li><a href="{% url 'blog:js' %}"><i class="bi bi-chevron-right"></i> JavaScripts</a></li>
                <li><a href="{% url 'blog:python' %}"><i class="bi bi-chevron-right"></i> Python</a></li>
                <li><a href="{% url 'blog:django' %}"><i class="bi bi-chevron-right"></i> Django</a></li>
              </ul>
            </div>

            {% else %}

            {% for post in page_object %}
            <h3 class="category-title">Category: {{ post.categories }}</h3>
            {% if tag %}
            <h5> Posts tagged with {{ tag.name }} <h5>
              {% endif %}
            <div class="post-meta">
              <h3 class="category-title">Tags:
                {% for tag in post.tags.all %} 
                <a class="caption" href="{% url "blog:post_list_by_tag" tag.slug %}">
                  {{ tag.name }} </a> {% if not forloop.last %}| {% endif %}
                {% endfor %}
              </h3>
            </div>

            <div class="d-md-flex post-entry-2 half">
              <a href="{{ post.get_absolute_url }}" class="me-4 thumbnail">
                <img src="{{ post.image.url }}" alt="" class="img-fluid">
              </a>
              <div>
                <div class="post-meta"><span class="date">{{ post.categories }}</span> <span class="mx-1">&bullet;</span> <span>{{ post.publish }}</span></div>
                <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                <p>{{ post.body|truncatewords:45|linebreaks }}</p>
                <div class="d-flex align-items-center author">
                  <div class="photo"><img src="{{ post.author_pic.url }}" alt="" class="img-fluid"></div>
                  <div class="name">
                    <h3 class="m-0 p-0">{{ post.author.first_name }} {{ post.author.last_name }}</h3>
                  </div>
                </div>
              </div>
            </div>
             {% endfor %}
             {% include 'blog_templates/includes/paginator.html' with page=page_object %}

          <div class="col-md-3">
            <!-- ======= Sidebar ======= -->
            <div class="aside-block">

              <ul class="nav nav-pills custom-tab-nav mb-4" id="pills-tab" role="tablist">
                <li class="nav-item" role="presentation">
                  <button class="nav-link active" id="pills-popular-tab" data-bs-toggle="pill" data-bs-target="#pills-popular" type="button" role="tab" aria-controls="pills-popular" aria-selected="true">Popular</button>
                </li>
                <li class="nav-item" role="presentation">
                  <button class="nav-link" id="pills-trending-tab" data-bs-toggle="pill" data-bs-target="#pills-trending" type="button" role="tab" aria-controls="pills-trending" aria-selected="false">Trending</button>
                </li>
                <li class="nav-item" role="presentation">
                  <button class="nav-link" id="pills-latest-tab" data-bs-toggle="pill" data-bs-target="#pills-latest" type="button" role="tab" aria-controls="pills-latest" aria-selected="false">Latest</button>
                </li>
              </ul>

              <div class="tab-content" id="pills-tabContent">

                 <!-- Popular -->
                 {% get_most_commented_post as commented_post %}
                 <div class="tab-pane fade show active" id="pills-popular" role="tabpanel" aria-labelledby="pills-popular-tab">
                  {% for post in commented_post %}
                  <div class="post-entry-1 border-bottom">
                    <div class="post-meta"><span class="date">{{ post.categories }}</span> <span class="mx-1">&bullet;</span> <span>{{ post.publish }}</span></div>
                    <h2 class="mb-2"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                    <span class="author mb-3 d-block">{{ post.author.first_name}} {{ post.author.last_name}}</span>
                  </div>
                  {% endfor %}
              </div>     
               <!-- End Popular -->

              <!-- Trending -->
              {% show_trending_post %} 
              <!-- End Trending -->

              <!-- Latest -->
              {% show_latest_posts %} 
               <!-- End Latest -->
              

              </div>
            </div>

            <div class="aside-block">
              <h3 class="aside-title">Video</h3>
              <div class="video-post">
                <a href="{{ post.video.url }}" class="glightbox link-video">
                  <span class="bi-play-fill"></span>
                  <img src="assets/img/post-landscape-5.jpg" alt="" class="img-fluid">
                </a>
              </div>
            </div><!-- End Video -->

            <div class="aside-block">
              <h3 class="aside-title">Categories</h3>
              <ul class="aside-links list-unstyled">
                <li><a href="{% url 'blog:html' %}"><i class="bi bi-chevron-right"></i> HTML</a></li>
                <li><a href="{% url 'blog:css' %}"><i class="bi bi-chevron-right"></i> CSS</a></li>
                <li><a href="{% url 'blog:js' %}"><i class="bi bi-chevron-right"></i> JavaScripts</a></li>
                <li><a href="{% url 'blog:python' %}"><i class="bi bi-chevron-right"></i> Python</a></li>
                <li><a href="{% url 'blog:django' %}"><i class="bi bi-chevron-right"></i> Django</a></li>
              </ul>
            </div>
            
            {% endif %}
          </div>
        </div>
        </div>
      </div>
    </section>
  </main><!-- End #main -->

  {% endblock main_content %}

templates/blog_templates/contact.html
{% extends 'blog_templates/base.html' %}
{% load static %}

{% block main_content%}

<main id="main">
  <section id="contact" class="contact mb-5">
    <div class="container" data-aos="fade-up">

      <div class="row">
        <div class="col-lg-12 text-center mb-5">
          <h1 class="page-title">Contact us</h1>
        </div>
      </div>

      <div class="row gy-4">

        <div class="col-md-4">
          <div class="info-item">
            <i class="bi bi-geo-alt"></i>
            <h3>Address</h3>
            <address>26 Abiona Akinsanya Close, Oshodi/Isolo, Lagos, Nigeria.</address>
          </div>
        </div><!-- End Info Item -->

        <div class="col-md-4">
          <div class="info-item info-item-borders">
            <i class="bi bi-phone"></i>
            <h3>Phone Number</h3>
            <p><a href="tel:+2348112079469">+234 811 207 9469</a></p>
          </div>
        </div><!-- End Info Item -->

        <div class="col-md-4">
          <div class="info-item">
            <i class="bi bi-envelope"></i>
            <h3>Email</h3>
            <p><a href="mailto:aghason.emmanuel@gmail.com">aghason.emmanuel@gmail.com</a></p>
          </div>
        </div><!-- End Info Item -->

      </div>

      <div class="form mt-5">
        <form action="forms/contact.php" method="post" role="form" class="php-email-form">
          <div class="row">
            <div class="form-group col-md-6">
              <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
            </div>
            <div class="form-group col-md-6">
              <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
            </div>
          </div>
          <div class="form-group">
            <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
          </div>
          <div class="form-group">
            <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
          </div>
          <div class="my-3">
            <div class="loading">Loading</div>
            <div class="error-message"></div>
            <div class="sent-message">Your message has been sent. Thank you!</div>
          </div>
          <div class="text-center"><button type="submit">Send Message</button></div>
        </form>
      </div><!-- End Contact Form -->

    </div>
  </section>

</main><!-- End #main -->

{% endblock main_content %}

  

templates/blog_templates/index.html
{% extends 'blog_templates/base.html' %}
{% load static %}

{% block main_content %}

  <main id="main">

    <!-- ======= Hero Slider Section ======= -->
    {% include 'blog_templates/includes/slider.html' %}
    <!-- End Hero Slider Section -->

    <!-- ======= Post HTML Section ======= -->
    <section id="posts" class="posts">
      <div class="container" data-aos="fade-up">
        {% include 'blog_templates/includes/html.html' %}
      </div>
    </section> <!-- End Post HTML Section -->

    <!-- ======= CSS Category Section ======= -->
      {% include 'blog_templates/includes/css.html' %}
      <!-- End CSS Category Section -->

    <!-- ======= JavaScript Category Section ======= -->
    {% include 'blog_templates/includes/javascript.html' %}
    <!-- End JavaScript Category Section -->

    <!-- ======= Python Category Section ======= -->
    {% include 'blog_templates/includes/python.html' %}
    <!-- End Python Category Section -->

    <!-- ======= Django Category Section ======= -->
    {% include 'blog_templates/includes/django.html' %}
    <!-- End Django Category Section -->

  </main>
  <!-- End #main -->

  {% endblock main_content%}

templates/blog_templates/single-post.html
{% extends 'blog_templates/base.html' %}
{% load static %}
{% load blog_tags %}
{% block Stylesheet %}
      <!-- Toastr -->
      <link rel="stylesheet" href="{% static 'admin-assets/css/toastr.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'admin-assets/css/bootstrap.min.css' %}">
      <!-- themify-icons line icon -->
{% endblock Stylesheet %}

 {% block main_content %}
 <main id="main">

  <section class="single-post-content">
    <div class="container">
      <div class="row">
        <div class="col-md-9 post-content">

          <!-- ======= Single Post Content ======= -->
          <div class="single-post">
            <div class="post-meta"><span class="date">{{ post.categories }}</span> <span class="mx-1">&bullet;</span> <span>{{ post.publish }}</span></div>
            <h1 class="mb-5">{{ post.title }}</h1><div class="post-meta"><span class="link">Tags: {{ post.tags.all|join:", " }}</span>.</div>
            <p>{{ post.body }}</p>

            <figure class="my-4">
              <img src="{{ post.image.url }}" alt="" class="img-fluid">
            </figure>
            <p>{{ post.extra }}</p>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-default">
              Share post <i class="bi-share"></i>
            </button>

    <div class="modal fade" id="modal-default" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
        <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="post" role="form" action="{% url 'blog:share_post' post.id %}">
          {% csrf_token %}
          <div class="mb-3">
            {{ share_form.name.errors }}
            {{ share_form.name.label}}
            {{ share_form.name }}
          </div>

          <div class="mb-3">
            {{ share_form.email.errors }}
            {{ share_form.email.label}}
            {{ share_form.email }}
          </div>

          <div class="mb-3">
            {{ share_form.to.errors }}
            {{ share_form.to.label}}
            {{ share_form.to }}
          </div>

          <div class="mb-3">
            {{ share_form.comments.errors }}
            {{ share_form.comments.label}}
            {{ share_form.comments }}
          </div>
    </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Send message</button>
      </div>
    </form>
    </div>
  </div>
</div>
            
          </div><!-- End Single Post Content -->

          <!-- ======= Comments ======= -->
          <div class="comments">
            {% if comment %}
            <h2>Your comment has been added.</h2>
            <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
            {% else %}
            {% include 'blog_templates/includes/comments.html' %}
             {% endif %}

          </div><!-- End Comments -->

        </div>
        <div class="col-md-3">
          <!-- ======= Sidebar ======= -->
          <div class="aside-block">

            <ul class="nav nav-pills custom-tab-nav mb-4" id="pills-tab" role="tablist">
              <li class="nav-item" role="presentation">
                <button class="nav-link active" id="pills-popular-tab" data-bs-toggle="pill" data-bs-target="#pills-popular" type="button" role="tab" aria-controls="pills-popular" aria-selected="true">Similar</button>
              </li>
              <li class="nav-item" role="presentation">
                <button class="nav-link" id="pills-trending-tab" data-bs-toggle="pill" data-bs-target="#pills-trending" type="button" role="tab" aria-controls="pills-trending" aria-selected="false">Trending</button>
              </li>
              <li class="nav-item" role="presentation">
                <button class="nav-link" id="pills-latest-tab" data-bs-toggle="pill" data-bs-target="#pills-latest" type="button" role="tab" aria-controls="pills-latest" aria-selected="false">Latest</button>
              </li>
            </ul>

            <div class="tab-content" id="pills-tabContent">

               <!-- Similar -->
               {% include 'blog_templates/sidebar/similar.html' %} 
               <!-- End Similar -->

              <!-- Trending -->
              {% show_trending_post %} 
              <!-- End Trending -->

              <!-- Latest -->
              {% show_latest_posts %} 
               <!-- End Latest -->

            </div>
          </div>

          <div class="aside-block">
            <h3 class="aside-title">Video</h3>
            <div class="video-post">
              <a href="{{ video}}" class="glightbox link-video">
                <span class="bi-play-fill"></span>
                <img src="assets/img/post-landscape-5.jpg" alt="" class="img-fluid">
              </a>
            </div>
          </div><!-- End Video -->

          <div class="aside-block">
            <h3 class="aside-title">Categories</h3>
            <ul class="aside-links list-unstyled">
              <li><a href="{% url 'blog:html' %}"><i class="bi bi-chevron-right"></i> HTML</a></li>
                <li><a href="{% url 'blog:css' %}"><i class="bi bi-chevron-right"></i> CSS</a></li>
                <li><a href="{% url 'blog:js' %}"><i class="bi bi-chevron-right"></i> JavaScripts</a></li>
                <li><a href="{% url 'blog:python' %}"><i class="bi bi-chevron-right"></i> Python</a></li>
                <li><a href="{% url 'blog:django' %}"><i class="bi bi-chevron-right"></i> Django</a></li>
            </ul>
          </div><!-- End Categories -->
        
        </div>
      </div>
    </div>
  </section>
</main><!-- End #main -->
{% endblock main_content %}

{% block custom_js %}
<script type="text/javascript" src="{% static 'admin-assets/js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'admin-assets/js/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'admin-assets/js/popper.min.js' %}"></script>
<script type="text/javascript" src="{% static 'admin-assets/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'admin-assets/js/script.min.js' %}"></script>
<!-- SweetAlert2 -->
<script src="{% static 'admin-assets/js/sweetalert2.min.js' %}"></script>
<!-- Toastr -->
<script src="{% static 'admin-assets/js/toastr.min.js' %}"></script>
{% endblock custom_js %}