Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls', namespace='blog',)),
    path('blog-admin/', include('adminapp.urls', namespace="blog_admin"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/urls.py
from django.urls import path
from blogapp import views

app_name = 'blog'

urlpatterns = [
path('', views.index, name='index'),
path('categories', views.categories, name='categories'),
path('categories/tag/<slug:tag_slug>', views.categories, name='post_list_by_tag'),
path('categories/html', views.html, name='html'),
path('categories/css', views.css, name='css'),
path('categories/js', views.js, name='js'),
path('categories/python', views.python, name='python'),
path('categories/django', views.django, name='django'),
path('about', views.about, name='about'),
path('contact', views.contact, name='contact'),
path('<int:year>/<int:month>/<int:day>/<slug:post>', views.post_detail, name='post_detail'),
path('share-post/<int:post_id>', views.share_post, name='share_post'),
path('<int:post_id>/comment', views.post_comment, name='post_comment'),
path('login', views.user_login, name='login'),
path('DoLogin', views.DoLogin, name='do_login'),
path('logout', views.user_logout, name='logout'),
]

templates/blog_templates/includes/comments.html
{% load static %}
   {% with comments.count as total_comments %}
<h5 class="comment-title py-4">{{ total_comments }} comment{{ total_comments|pluralize }}</h5>
  {% endwith %}
            <div class="comment d-flex mb-4">
              <div class="flex-shrink-0">
                <div class="avatar avatar-sm rounded-circle">
                  <img class="avatar-img" src="assets/img/person-5.jpg" alt="" class="img-fluid">
                </div>
              </div>
              <div class="flex-grow-1 ms-2 ms-sm-3">
                {% for comment in comments %}
                <div class="comment-meta d-flex align-items-baseline">
                  <h6 class="me-2">{{ comment.name }}</h6>
                  <span class="text-muted">{{ comment.created }}</span>
                </div>
                <div class="comment-body">
                  {{ comment.body|truncatewords:20|linebreaks }}
                </div>
                {% empty %}
                  <p>Be the first to comment.</p>
                {% endfor %}
                {% include 'blog_templates/includes/comments_form.html' with form=form %}

                {% comment %} <div class="comment-replies bg-light p-3 mt-3 rounded">
                  <h6 class="comment-replies-title mb-4 text-muted text-uppercase">2 replies</h6>

                  <div class="reply d-flex mb-4">
                    <div class="flex-shrink-0">
                      <div class="avatar avatar-sm rounded-circle">
                        <img class="avatar-img" src="assets/img/person-4.jpg" alt="" class="img-fluid">
                      </div>
                    </div>
                    <div class="flex-grow-1 ms-2 ms-sm-3">
                      <div class="reply-meta d-flex align-items-baseline">
                        <h6 class="mb-0 me-2">Brandon Smith</h6>
                        <span class="text-muted">2d</span>
                      </div>
                      <div class="reply-body">
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                      </div>
                    </div>
                  </div>

                  <div class="reply d-flex">
                    <div class="flex-shrink-0">
                      <div class="avatar avatar-sm rounded-circle">
                        <img class="avatar-img" src="assets/img/person-3.jpg" alt="" class="img-fluid">
                      </div>
                    </div>
                    <div class="flex-grow-1 ms-2 ms-sm-3">
                      <div class="reply-meta d-flex align-items-baseline">
                        <h6 class="mb-0 me-2">James Parsons</h6>
                        <span class="text-muted">1d</span>
                      </div>
                      <div class="reply-body">
                        James ipsum dolor sit amet, consectetur adipisicing elit. Distinctio dolore sed eos sapiente, praesentium.
                      </div>
                    </div>
                  </div>
                </div> {% endcomment %}
              </div>
            </div>
            

templates/blog_templates/includes/comments_form.html
<div class="row justify-content-center mt-5">
  <div class="col-lg-12">
    <h5 class="comment-title">Leave a Comment</h5>
    <div class="row">
      <form action="{% url 'blog:post_comment' post.id %}" method="post" role="form">
           {% csrf_token %}
        <div class="col-lg-6 mb-3">
          {{ form.name.errors }}
          {{ form.name.label }}
          {{ form.name }}
        </div>
        <div class="col-lg-6 mb-3">
          {{ form.email.errors }}
          {{ form.email.label }}
          {{ form.email }}
        </div>
        <div class="col-12 mb-3">
          {{ form.body.errors }}
          {{ form.body.label}}
          {{ form.body }}
        </div>
        <div class="col-12">
          <input type="submit" class="btn btn-primary" value="Post comment">
        </div>
      </form>
    </div>
  </div>
</div>

templates/blog_templates/includes/css.html
    {% load static %}
        <div class="container" data-aos="fade-up">
  
          <div class="section-header d-flex justify-content-between align-items-center mb-5">
            <h2>CSS</h2>
            <div><a href="" class="more">See All CSS</a></div>
          </div>
  
          <div class="row">
            <div class="col-md-9">
  
              <div class="d-lg-flex post-entry-2">
                <a href="{{ css_single.get_absolute_url }}" class="me-4 thumbnail mb-4 mb-lg-0 d-inline-block">
                  <img src="{{ css_single.image.url }}" alt="" class="img-fluid">
                </a>
                <div>
                  <div class="post-meta"><span class="date">{{ css_single.categories }}</span> <span class="mx-1">&bullet;</span> <span>{{ css_single.publish }}</span></div>
                  <h3><a href="{{ css_single.get_absolute_url }}">{{ css_single.title }}</a></h3>
                  <p>{{ css_single.body|truncatewords:40|linebreaks }}</p>
                  <div class="d-flex align-items-center author">
                    <div class="photo"><img src="{{ css_single.author.profile_pic.url }}" alt="photo" class="img-fluid"></div>
                    <div class="name">
                      <h3 class="m-0 p-0">{{ css_single.author.first_name }} {{ css_single.author.last_name }}</h3>
                    </div>
                  </div>
                </div>
              </div>
  
              <div class="row">
                <div class="col-lg-4">
                  <div class="post-entry-1 border-bottom">
                    <a href="single-post.html"><img src="{% static 'blog-assets/img/post-landscape-1.jpg' %}" alt="" class="img-fluid"></a>
                    <div class="post-meta"><span class="date">{{ css_single.categories }}</span> <span class="mx-1">&bullet;</span> <span>Nov. 29, 2022, 11:15 P.M.</span></div>
                    <h2 class="mb-2"><a href="single-post.html">CSS Text Properties</a></h2>
                    <div class="d-flex align-items-center author">
                        <div class="photo"><img src="{{ css_single.author_pic.url }}" alt="photo" class="img-fluid"></div>
                        <span class="author mb-3 d-block">{{ css_single.author.first_name }} {{ css_single.author.last_name }}</span>
                    </div>
                    <p class="mb-4 d-block">
                      Specifying two or more
                      font values is known as specifying a font stack. If the browser does not support the
                      primary font, it displays the second font family indicated and if the browser does not
                      support the second font family value, the browser uses the...
                    </p>
                  </div>
  
                  <div class="post-entry-1">
                    <div class="post-meta"><span class="date">{{ css_single.categories }}</span> <span class="mx-1">&bullet;</span> <span>Dec. 9, 2022, 2:38 P.M.</span></div>
                    <h2 class="mb-2"><a href="single-post.html">Creating An External Style Sheet</a></h2>
                    <span class="author mb-3 d-block">{{ css_single.author.first_name }} {{ css_single.author.last_name }}</span>
                  </div>
                </div>
                <div class="col-lg-8">
                  <div class="post-entry-1">
                    <a href="single-post.html"><img src="{% static 'blog-assets/img/post-landscape-2.jpg' %}" alt="" class="img-fluid"></a>
                    <div class="post-meta"><span class="date">{{ css_single.categories }}</span> <span class="mx-1">&bullet;</span> <span>Jul. 27, 2022, 11:15 A.M.</span></div>
                    <h2 class="mb-2"><a href="single-post.html">How To Use Float and Clear Properties</a></h2>
                    <span class="author mb-3 d-block">{{ css_single.author.first_name }} {{ css_single.author.last_name }}</span>
                    <p class="mb-4 d-block">
                      The float property allows you to position an element to the right or left of other elements, while remaining within its parent element. The float property has
                      four valid values: left, right, inherit, and none. The left value floats an element left. The right value floats an element right. The inherit value
                      floats an element with the same value as its parent element. The none value does...
                    </p>
                  </div>
                </div>
              </div>
            </div>
              <!-- end of col-md-9 -->
              
              <!-- right side content -->
            <div class="col-md-3">
              <div class="post-entry-1 border-bottom">
                <div class="post-meta"><span class="date">{{ css_single.categories }}</span> <span class="mx-1">&bullet;</span> <span>Jul 28, 2022, 11:18 A.M.</span></div>
                <h2 class="mb-2"><a href="single-post.html">Aligning Webpage Content Using CSS</a></h2>
                <span class="author mb-3 d-block">{{ css_single.author.first_name }} {{ css_single.author.last_name }}</span>
              </div>
  
              <div class="post-entry-1 border-bottom">
                <div class="post-meta"><span class="date">{{ css_single.categories }}</span> <span class="mx-1">&bullet;</span> <span>Jul. 29, 2022, 4:31 P.M.</span></div>
                <h2 class="mb-2"><a href="single-post.html">Learn How To Style List for Navigation Links With CSS</a></h2>
                <span class="author mb-3 d-block">{{ css_single.author.first_name }} {{ css_single.author.last_name }}</span>
              </div>
  
              <div class="post-entry-1 border-bottom">
                <div class="post-meta"><span class="date">{{ css_single.categories }}</span> <span class="mx-1">&bullet;</span> <span>Jul. 29, 2022, 3:15 P.M.</span></div>
                <h2 class="mb-2"><a href="single-post.html">CSS List Properties You Should Know</a></h2>
                <span class="author mb-3 d-block">{{ css_single.author.first_name }} {{ css_single.author.last_name }}</span>
              </div>
  
              <div class="post-entry-1 border-bottom">
                <div class="post-meta"><span class="date">{{ css_single.categories }}</span> <span class="mx-1">&bullet;</span> <span>Jul. 30, 2022, 8:46 A.M.</span></div>
                <h2 class="mb-2"><a href="single-post.html">Making Responsive Images</a></h2>
                <span class="author mb-3 d-block">{{ css_single.author.first_name }} {{ css_single.author.last_name }}</span>
              </div>
  
              <div class="post-entry-1 border-bottom">
                <div class="post-meta"><span class="date">{{ css_single.categories }}</span> <span class="mx-1">&bullet;</span> <span>Jul. 30, 2022, 10:13 A.M.</span></div>
                <h2 class="mb-2"><a href="single-post.html">How To Create a Style Rule for the Footer Element</a></h2>
                <span class="author mb-3 d-block">{{ css_single.author.first_name }} {{ css_single.author.last_name }}</span>
              </div>
  
              <div class="post-entry-1 border-bottom">
                <div class="post-meta"><span class="date">{{ css_single.categories }}</span> <span class="mx-1">&bullet;</span> <span>Jul. 30, 2022, 12:09 A.M.</span></div>
                <h2 class="mb-2"><a href="single-post.html">CSS Reset</a></h2>
                <span class="author mb-3 d-block">{{ css_single.author.first_name }} {{ css_single.author.last_name }}</span>
              </div>
            </div> <!--End of right side content -->
          
          </div> <!-- End of row main row -->
        </div>
      </section>

templates/blog_templates/includes/django.html
{% load static %}
<section class="category-section">
    <div class="container" data-aos="fade-up">

      <div class="section-header d-flex justify-content-between align-items-center mb-5">
        <h2>Django</h2>
        <div><a href="category.html" class="more">See All Django</a></div>
      </div>

      <div class="row">
        <div class="col-md-9">

          <div class="d-lg-flex post-entry-2">
            <a href="single-post.html" class="me-4 thumbnail mb-4 mb-lg-0 d-inline-block">
              <img src="{% static 'blog-assets/img/post-landscape-6.jpg' %}" alt="" class="img-fluid">
            </a>
            <div>
              <div class="post-meta"><span class="date">CSS</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
              <h3><a href="single-post.html">What is the son of Football Coach John Gruden, Deuce Gruden doing Now?</a></h3>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio placeat exercitationem magni voluptates dolore. Tenetur fugiat voluptates quas, nobis error deserunt aliquam temporibus sapiente, laudantium dolorum itaque libero eos deleniti?</p>
              <div class="d-flex align-items-center author">
                <div class="photo"><img src="{% static 'blog-assets/img/person-2.jpg' %}" alt="photo" class="img-fluid"></div>
                <div class="name">
                  <h3 class="m-0 p-0">Wade Warren</h3>
                </div>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-lg-4">
              <div class="post-entry-1 border-bottom">
                <a href="single-post.html"><img src="{% static 'blog-assets/img/post-landscape-1.jpg' %}" alt="" class="img-fluid"></a>
                <div class="post-meta"><span class="date">Python</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
                <h2 class="mb-2"><a href="single-post.html">11 Work From Home Part-Time Jobs You Can Do Now</a></h2>
                <div class="d-flex align-items-center author">
                    <div class="photo"><img src="{% static 'blog-assets/img/person-2.jpg' %}" alt="photo" class="img-fluid"></div>
                    <span class="author mb-3 d-block">Jenny Wilson</span>
                </div>
                <p class="mb-4 d-block">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero temporibus repudiandae, inventore pariatur numquam cumque possimus</p>
              </div>

              <div class="post-entry-1">
                <div class="post-meta"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
                <h2 class="mb-2"><a href="single-post.html">5 Great Startup Tips for Female Founders</a></h2>
                <span class="author mb-3 d-block">Jenny Wilson</span>
              </div>
            </div>
            <div class="col-lg-8">
              <div class="post-entry-1">
                <a href="single-post.html"><img src="{% static 'blog-assets/img/post-landscape-2.jpg' %}" alt="" class="img-fluid"></a>
                <div class="post-meta"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
                <h2 class="mb-2"><a href="single-post.html">How to Avoid Distraction and Stay Focused During Video Calls?</a></h2>
                <span class="author mb-3 d-block">Jenny Wilson</span>
                <p class="mb-4 d-block">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero temporibus repudiandae, inventore pariatur numquam cumque possimus</p>
              </div>
            </div>
          </div>
        </div>
          <!-- end of col-md-9 -->
          
          <!-- right side content -->
        <div class="col-md-3">
          <div class="post-entry-1 border-bottom">
            <div class="post-meta"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '26</span></div>
            <h2 class="mb-2"><a href="single-post.html">How to Avoid Distraction and Stay Focused During Video Calls?</a></h2>
            <span class="author mb-3 d-block">Jenny Wilson</span>
          </div>

          <div class="post-entry-1 border-bottom">
            <div class="post-meta"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '25</span></div>
            <h2 class="mb-2"><a href="single-post.html">17 Pictures of Medium Length Hair in Layers That Will Inspire Your New Haircut</a></h2>
            <span class="author mb-3 d-block">Jenny Wilson</span>
          </div>

          <div class="post-entry-1 border-bottom">
            <div class="post-meta"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
            <h2 class="mb-2"><a href="single-post.html">9 Half-up/half-down Hairstyles for Long and Medium Hair</a></h2>
            <span class="author mb-3 d-block">Jenny Wilson</span>
          </div>

          <div class="post-entry-1 border-bottom">
            <div class="post-meta"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
            <h2 class="mb-2"><a href="single-post.html">Life Insurance And Pregnancy: A Working Mom’s Guide</a></h2>
            <span class="author mb-3 d-block">Jenny Wilson</span>
          </div>

          <div class="post-entry-1 border-bottom">
            <div class="post-meta"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
            <h2 class="mb-2"><a href="single-post.html">The Best Homemade Masks for Face (keep the Pimples Away)</a></h2>
            <span class="author mb-3 d-block">Jenny Wilson</span>
          </div>

          <div class="post-entry-1 border-bottom">
            <div class="post-meta"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
            <h2 class="mb-2"><a href="single-post.html">10 Life-Changing Hacks Every Working Mom Should Know</a></h2>
            <span class="author mb-3 d-block">Jenny Wilson</span>
          </div>
        </div> <!--End of right side content -->
      
      </div> <!-- End of row main row -->
    </div>
  </section>

templates/blog_templates/includes/header.html
{% load static %}
<div class="container-fluid container-xl d-flex align-items-center justify-content-between">

    <a href="{% url 'blog:index' %}" class="logo d-flex align-items-center">
      <img src="{% static 'blog-assets/img/logo.png' %}" alt="">
      <h1>Emmi Blog</h1>
    </a>

    <nav id="navbar" class="navbar">
      <ul>
        <li>
          {% url 'blog:index' as index %}
          <a href="{{ index }}">Blog</a></li>
        <li class="dropdown"><a href="{% url 'blog:categories' %}"><span>Categories</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
          <ul>
            <li><a href="{% url 'blog:html' %}">HTML</a></li>
            <li><a href="{% url 'blog:css' %}">CSS</a></li>
            <li><a href="{% url 'blog:js' %}">JavaScripts</a></li>
            <li><a href="{% url 'blog:python' %}">Python</a></li>
            <li><a href="{% url 'blog:django' %}">Django</a></li>
          </ul>
        </li>

        <li><a href="{% url 'blog:about' %}">About</a></li>
        <li><a href="{% url 'blog:contact' %}">Contact</a></li>
        <li><a href="{% url 'blog:login' %}">Login</a></li>
      </ul>
    </nav><!-- .navbar -->

    <div class="position-relative">
      <a target='_blank' href="https://www.facebook.com/profile.php?id=100077257599929" class="mx-2"><span class="bi-facebook"></span></a>
      <a target='_blank' href="https://twitter.com/emmi_dev01" class="mx-2"><span class="bi-twitter"></span></a>
      <a target='_blank' href="https://www.youtube.com/@emmidev" class="mx-2"><span class="bi-youtube"></span></a>

      <a href="#" class="mx-2 js-search-open"><span class="bi-search"></span></a>
      <i class="bi bi-list mobile-nav-toggle"></i>

      <!-- ======= Search Form ======= -->
      <div class="search-form-wrap js-search-form-wrap">
        <form method="get" action="{% url 'blog:categories' %}" class="search-form">
          {% csrf_token %}
          <button type="get" class="btn js-search"><span class="icon bi-search"></span></button>
          {{ search_form.query.errors }}
            {{ search_form.query }}
          <button class="btn js-search-close"><span class="bi-x"></span></button>
        </form>
      </div><!-- End Search Form -->

    </div>

  </div>

templates/blog_templates/includes/html.html
{% load static %}
<div class="row g-5">
    <div class="col-lg-4">
      <div class="post-entry-1 lg">
        <a href="{{ html_single.get_absolute_url }}"><img src="{{ html_single.image.url }}" alt="" class="img-fluid"></a>
        <div class="post-meta"><span class="date">{{ html_single.categories }}</span> <span class="mx-1">&bullet;</span> <span>{{ html_single.publish }}</span></div>
        <h2><a href="{{ html_single.get_absolute_url }}">{{ html_single.title }}</a></h2>
        <p class="mb-4 d-block">
          {{ html_single.body|truncatewords:90|linebreaks }}
        </p>
        <div class="d-flex align-items-center author">
          <div class="photo"><img src="{{ html_single.author.profile_pic.url }}" alt="" class="img-fluid"></div>
          <div class="name">
            <h3 class="m-0 p-0">{{ html_single.author.first_name }} {{ html_single.author.last_name }}</h3>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-8">
      <div class="row g-5">
        <div class="col-lg-4 border-start custom-border">
          {% for html in html_posts %}
          <div class="post-entry-1">
            <a href="{{ html.get_absolute_url }}"><img src="{{ html.image.url }}" alt="" class="img-fluid"></a>
            <div class="post-meta"><span class="date">{{ html.categories }}</span> <span class="mx-1">&bullet;</span> <span>{{ html.publish }}</span></div>
            <h2><a href="{{ html.get_absolute_url }}">{{ html.title }}</a></h2>
          </div>
          {% endfor %}
        </div>

        <div class="col-lg-4 border-start custom-border">
          <div class="post-entry-1">
            <a href="single-post.html"><img src="/static/blog-assets/img/post-landscape-3.jpg" alt="" class="img-fluid"></a>
            <div class="post-meta"><span class="date">Business</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
            <h2><a href="single-post.html">6 Easy Steps To Create Your Own Cute Merch For Instagram</a></h2>
          </div>
          <div class="post-entry-1">
            <a href="single-post.html"><img src="/static/blog-assets/img/post-landscape-6.jpg" alt="" class="img-fluid"></a>
            <div class="post-meta"><span class="date">Tech</span> <span class="mx-1">&bullet;</span> <span>Mar 1st '22</span></div>
            <h2><a href="single-post.html">10 Life-Changing Hacks Every Working Mom Should Know</a></h2>
          </div>
          <div class="post-entry-1">
            <a href="single-post.html"><img src="/static/blog-assets/img/post-landscape-8.jpg" alt="" class="img-fluid"></a>
            <div class="post-meta"><span class="date">Travel</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
            <h2><a href="single-post.html">5 Great Startup Tips for Female Founders</a></h2>
          </div>
        </div>

        <!-- Trending Section -->
        <div class="col-lg-4">

          {% include 'blog_templates/includes/trending.html' %}

        </div> <!-- End Trending Section -->
      </div>
    </div>

  </div> <!-- End .row -->

templates/blog_templates/includes/paginator.html
<div class="text-start py-4">
    <div class="custom-pagination text-center">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}" class="prev">Prevous</a>
        {% endif %}
        <span class ="mx-1">
          Page {{ page.number }} of {{ page.paginator.num_pages }}
        </span>
    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </div>
  </div>
</div>

templates/blog_templates/includes/slider.html
<section id="hero-slider" class="hero-slider">
    <div class="container-md" data-aos="fade-in">
      <div class="row">
        <div class="col-12">
          <div class="swiper sliderFeaturedPosts">
            <div class="swiper-wrapper">
              {% for slider in sliders %}
              <div class="swiper-slide">
                <a href="{{ slider.get_absolute_url }}" class="img-bg d-flex align-items-end" style="background-image: url('{{ slider.image.url }}');">
                  <div class="img-bg-inner">
                    <h2>{{ slider.title }}</h2>
                    <p>{{ slider.body|truncatewords:40|linebreaks }}</p>
                  </div>
                </a>
              </div>
              {% endfor %}
            </div>

            <div class="custom-swiper-button-next">
              <span class="bi-chevron-right"></span>
            </div>
            <div class="custom-swiper-button-prev">
              <span class="bi-chevron-left"></span>
            </div>

            <div class="swiper-pagination">next</div>
          </div>
        </div>
      </div>
    </div>
  </section>

templates/blog_templates/includes/trending.html
<div class="trending">
    <h3>Trending</h3>
    {% for post in page_object %}
    <ul class="trending-post">
      <li>
        <a href="{{ post.get_absolute_url }}">
          <h3>{{ post.title }}</h3>
          <span class="author">{{ post.author.first_name }} {{ post.author.last_name }}</span>
        </a>
      </li>
      <li>
    </ul>
    {% endfor %}
    {% include 'blog_templates/includes/paginator.html' with page=page_object %}
  </div>